name = "n4"
main = "_worker.js"
compatibility_date = "2025-07-23"

keep_vars = true

[observability.logs]
enabled = true

kv-namespaces = [
{ binding = "KV", id = "bb86ceb70066453d9335bdb62492a378" }
]





